#part of mrogue, an interactive adventure game
#Copyright (C) 2017 Adrien Young and Tyler Soberanis
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

import game as main
import ai
import libtcodpy as libtcod
import pathfinding
import combat

# Monster Flags
NO_CORPSE = 1
IMMOBILE = 2
EVIL = 4
WEB_IMMUNE = 4
NO_BREATH = 8
LOW_PRIORITY = 16  # used for targeting

proto = {
    'monster_target': {
        'name': 'training dummy',
        'char': 'd',
        'color': libtcod.white,
        'hp': 5000000000,
        'strength_dice' : '0d0',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 0,
        'will': 0,
        'fortitude': 0,
        'accuracy': 0,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A training dummy stuffed with straw',
        'shred': 0,
    },
    'monster_cockroach': {
        'name': 'cockroach',
        'char': 'r',
        'color': libtcod.dark_red,
        'body_type': 'insect',
        'hp': 1,
        'strength_dice' : '1d8',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 0,
        'will': 0,
        'fortitude': 0,
        'accuracy': 19,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'An irritating, crawling insect. Easily defeated, but a nuisance nonetheless.',
        'shred': 1,
        'subtype':'insect',
        'zombie':'monster_zombie_vermin'
    },
    'monster_snake': {
        'name': 'water snake',
        'char': 's',
        'color': libtcod.dark_green,
        'hp': 10,
        'strength_dice' : '1d4',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 12,
        'will': 5,
        'fortitude': 5,
        'accuracy': 20,
        'move_speed': 0.9,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A venomous water snake. Its bite takes effect slowly, but causes a great deal of harm.',
        'attributes': ['attribute_fast_swimmer'],
        'on_hit': ['on_hit_poison'],
        'resistances' : {'poisoned' : 'immune'},
        'shred': 1,
        'pierce': 1,
        'subtype':'beast',
        'body_type':'beast',
        'stealth': 5,
    },
    'monster_centipede': {
        'name': 'centipede',
        'char': 'c',
        'color': libtcod.flame,
        'body_type': 'insect',
        'hp': 30,
        'strength_dice' : '1d12',
        'attack_bonus' : 2,
        'armor': 1,
        'evasion': 6,
        'will': 1,
        'fortitude': 3,
        'accuracy': 24,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'difficulty': 1,
        'ai': ai.AI_Default,
        'description': 'Many-legged arthropod with a stinging bite.',
        'on_hit': ['on_hit_sting'],
        'resistances' : {'poisoned' : 'immune'},
        'shred': 2,
        'subtype':'insect',
    },
    'monster_rotting_zombie': {
        'name': 'rotting zombie',
        'char': 'z',
        'color': libtcod.dark_chartreuse,
        'hp': 45,
        'strength_dice' : '1d7',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 4,
        'will': 0,
        'fortitude': 8,
        'accuracy': 19,
        'move_speed': 0.5,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A rotting corpse animated by some evil magic. It shambles slowly, but once it reaches its prey it latches on tight.',
        'resistances' : {'radiance' : -1},
        'on_hit': ['zombie_on_hit'],
        'shred': 1,
        'flags' : NO_CORPSE | EVIL,
        'modifier_category':'default',
        'subtype':'undead',
    },
    'monster_goblin': {
        'name': 'goblin lurker',
        'char': 'g',
        'color': libtcod.desaturated_green,
        'hp': 20,
        'strength_dice' : '2d9',
        'attack_bonus' : 0,
        'armor': 1,
        'evasion': 9,
        'will': 3,
        'fortitude': 5,
        'accuracy': 18,
        'move_speed': 0.8,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'Small vicious humanoid. Dangerous in groups.',
        'loot_level':-1,
        'equipment': [
            {'weapon_dagger':35,'weapon_club':35, 'none':30},
            {'none':80,'shield_leather_buckler':10,'shield_wooden_buckler':10}],
        'shred': 1,
        'modifier_category':'goblin',
        'subtype':'goblin',
    },
    'monster_goblin_warrior': {
        'name': 'goblin warrior',
        'char': 'g',
        'color': libtcod.gray,
        'hp': 40,
        'strength_dice' : '2d12',
        'attack_bonus' : 0,
        'armor': 2,
        'evasion': 9,
        'will': 3,
        'fortitude': 10,
        'accuracy': 23,
        'move_speed': 0.8,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'Small vicious humanoid that scavenged some equipment.',
        'loot_level':0,
        'equipment': [
            {'weapon_dagger':25,'weapon_longsword':30, 'weapon_hatchet':15, 'weapon_spear':15, 'weapon_mace':15},
            {'none':50,'shield_leather_buckler':10,'shield_wooden_buckler':25,'shield_iron_buckler':10,'shield_kite_shield':5,},
            {'none':50,'equipment_leather_armor':40, 'equipment_mail_armor':10}],
        'shred': 1,
        'modifier_category':'goblin',
        'subtype':'goblin',
    },
    'monster_goblin_chief': {
        'name': 'goblin chief',
        'char': 'g',
        'color': libtcod.dark_yellow,
        'hp': 45,
        'strength_dice' : '2d16',
        'attack_bonus' : 10,
        'armor': 2,
        'evasion': 9,
        'will': 10,
        'fortitude': 10,
        'accuracy': 23,
        'move_speed': 0.9,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'Slightly larger, much more vicious humanoid that tells other goblins what to do.',
        'equipment': [
            {'weapon_spear':30,'weapon_longsword':40, 'weapon_hatchet':30},
            {'none':50,'shield_kite_shield':25, 'shield_round_shield':25},
            {'equipment_leather_armor':50, 'equipment_mail_armor':50}],
        'shred': 1,
        'modifier_category':'goblin',
        'subtype':'goblin',
    },
    'monster_goblin_priest': {
        'name': 'goblin priest',
        'char': 'g',
        'color': libtcod.pink,
        'hp': 24,
        'strength_dice' : '1d10',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 11,
        'will': 15,
        'fortitude': 5,
        'accuracy': 18,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Support,
        'description': 'A small, vicious humanoid, but also a devout follower of Splug, '
                       'who grants his priests the power to heal.',
        'loot_level': 0,
        'equipment': [{'equipment_cloth_robes':100}],
        'shred': 1,
        'modifier_category':'goblin',
        'subtype':'goblin',
        'attributes':['ability_heal_other'],
        'essence': [(25, 'life')],
    },
    'monster_goblin_wizard': {
        'name': 'goblin wizard',
        'char': 'g',
        'color': libtcod.blue,
        'hp': 30,
        'strength_dice' : '1d10',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 11,
        'will': 15,
        'fortitude': 2,
        'accuracy': 18,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'spell_power': 12,
        'ai': ai.AI_Default,
        'description': 'A small, vicious humanoid with a penchant for magical spells.',
        'loot_level': 0,
        'equipment': [{'equipment_cloth_robes':100}],
        'attributes': [{'ability_teleportal': 25, 'ability_time_bomb': 25, 'ability_haste': 25, 'ability_flame_wall': 25},
                       {'ability_teleportal': 25, 'ability_time_bomb': 25, 'ability_haste': 25, 'ability_flame_wall': 25},
                       {'ability_arcane_arrow': 100}],
        'shred': 1,
        'modifier_category':'goblin',
        'subtype':'goblin',
        'essence': [(25, 'arcane')],
    },
    'monster_goblin_champion': {
        'name': 'goblin champion',
        'char': 'g',
        'color': libtcod.flame,
        'hp': 85,
        'strength_dice' : '2d24',
        'attack_bonus' : 0,
        'armor': 3,
        'evasion': 11,
        'will': 5,
        'fortitude': 20,
        'accuracy': 32,
        'move_speed': 0.8,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A large vicious humanoid, covered in scars from its years in the goblin fighting pits. '
                       'It is armed with heavy gear and a throwing net, and has learned how to disarm opponents in '
                       'melee combat.',
        'loot_level':0,
        'equipment': [
            {'weapon_longsword':20, 'weapon_spear':20, 'weapon_mace':20, 'weapon_greatsword':8, 'weapon_dane_axe':8,'weapon_messer':8, 'weapon_halberd':8, 'weapon_warhammer':8},
            {'shield_iron_buckler':10,'shield_heater_shield':25, 'shield_escutcheon':25, 'shield_round_shield':20, 'shield_kite_shield':15, 'shield_tower_shield':5},
            {'equipment_mail_armor':40, 'equipment_brigandine' : 50, 'equipment_plate_armor' : 10},
            {'none' : 60, 'equipment_iron_helm': 20, 'equipment_great_helm' : 20}],
        'shred': 1,
        'modifier_category':'goblin',
        'subtype':'goblin',
        'attributes':['ability_throw_net'],
        'on_hit': ['on_hit_disarm'],
    },
    'monster_snow_kite': {
        'name': 'snow kite',
        'char': 'k',
        'color': libtcod.lightest_gray,
        'hp': 36,
        'strength_dice' : '1d24',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 12,
        'will': 5,
        'fortitude': 5,
        'accuracy': 24,
        'move_speed': 1.25,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'body_type': 'avian',
        'description': 'A predatory bird with white plumage flecked with gray. It glides with grace on chill winds, '
                       'searching for prey with its keen avian eyes.',
        'essence': [(50, 'cold')],
        'shred': 1,
        'subtype':'beast',
        'movement_type': pathfinding.FLYING
    },
    'monster_bomb_beetle': {
        'name': 'bomb beetle',
        'char': 'b',
        'color': libtcod.light_sepia,
        'body_type': 'insect',
        'hp': 15,
        'strength_dice' : '1d12',
        'attack_bonus' : 0,
        'armor': 3,
        'evasion': 6,
        'will': 3,
        'fortitude': 10,
        'accuracy': 22,
        'move_speed': 0.9,
        'attack_speed': 1.5,
        'death_function' : {
            'function': 'on_death_bomb',
            'damage': 30
        },
        'ai': ai.AI_Default,
        'description': 'A round brown beetle. A warm glow emanates from beneath its carapace.',
        'essence': [(20, 'fire')],
        'subtype':'insect',
    },
    'monster_giant_frog': {
        'name': 'giant frog',
        'char': 'f',
        'color': libtcod.lime,
        'hp': 35,
        'strength_dice' : '1d10',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 10,
        'will': 5,
        'fortitude': 5,
        'accuracy': 21,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'Unusually large amphibian that dwells in lakes and ponds. '
                       'Can grab unwary adventurers with its sticky tongue.',
        'attributes':['ability_grapel'],
        'essence': [(10, 'water'), (10, 'life')],
        'subtype':'beast',
        'movement_type': pathfinding.NORMAL | pathfinding.AQUATIC
    },
    'monster_necroling': {
        'name': 'necroling',
        'char': 'n',
        'color': libtcod.dark_violet,
        'hp': 30,
        'strength_dice' : '1d18',
        'attack_bonus' : 10,
        'armor': 2,
        'evasion': 12,
        'will': 10,
        'fortitude': 10,
        'accuracy': 19,
        'move_speed': 0.9,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': "A giant segmented worm covered in bony scales and reeking of death. It is drawn to fresh "
                       "corpses, animating them by means of some dark magic.",
        'attributes':['ability_raise_zombie'],
        'essence': [(35, 'death')],
        'flags' : NO_CORPSE | EVIL,
        'subtype':'undead',
    },
    'monster_verman': {
        'name': 'verman',
        'char': 'v',
        'color': libtcod.amber,
        'hp': 45,
        'strength_dice' : '1d8',
        'attack_bonus' : 4,
        'armor': 2,
        'evasion': 13,
        'will': 12,
        'fortitude': 7,
        'accuracy': 21,
        'move_speed': 0.75,
        'attack_speed': 1.8,
        'ai': ai.AI_Default,
        'description': "A filthy rat-faced humanoid clad with ragged scraps of leather. "
                       "The vermin of the dungeon are drawn to his stench.",
        'attributes':['ability_summon_vermin'],
        'shred': 1,
        'essence': [(10, 'earth')],
        'subtype':'verman',
    },
    'monster_marsh_hunter': {
        'name': 'marsh hunter',
        'char': 'h',
        'color': libtcod.desaturated_green,
        'hp': 20,
        'strength_dice' : '1d10',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 14,
        'will': 8,
        'fortitude': 2,
        'accuracy': 18,
        'move_speed': 0.75,
        'attack_speed': 0.33,
        'range':5,
        'on_hit': ['on_hit_poison'],
        'ai': ai.AI_Default,
        'description': 'Lurking hunter, armed with a bow with poisoned arrows',
        'shred': 0,
        'subtype':'human',
    },
    'monster_reeker': {
        'name': 'reeker',
        'char': 24,
        'color': libtcod.light_fuchsia,
        'body_type': 'plant',
        'hp': 45,
        'strength_dice' : '0d0',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 0,
        'will': 0,
        'fortitude': 0,
        'accuracy': 0,
        'ai': ai.AI_Reeker,
        'description': 'A short, stocky fungus that emits puffs of foul-smelling gas.',
        'resistances': {'confusion' : 'immune', 'stunned' : 'immune', 'fire' : -1},
        'essence': [(25, 'life')],
        'flags' : NO_CORPSE | IMMOBILE | NO_BREATH,
        'subtype':'plant',
    },
    'monster_blastcap': {
        'name': 'blastcap',
        'char': 5,
        'color': libtcod.gold,
        'body_type': 'plant',
        'hp': 1,
        'strength_dice' : '0d0',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 0,
        'will': 0,
        'fortitude': 0,
        'accuracy': 0,
        'description': 'A volatile yellow fungus covered in softly glowing nodules. If disrupted, it bursts in a '
                       'deafening crack, stunning anything adjacent (but not diagonally) for several turns.',
        'resistances': {'confusion' : 'immune', 'stunned' : 'immune'},
        'death_function': {
            'function':'on_death_blastcap',
            'duration': 4,
        },
        'flags' : NO_CORPSE | IMMOBILE | NO_BREATH | LOW_PRIORITY,
        'subtype':'plant',
        'team' : 'neutral'
    },
    'monster_golem': {
        'name': 'golem',
        'char': 'G',
        'color': libtcod.sepia,
        'hp': 100,
        'strength_dice' : '1d20',
        'attack_bonus' : 20,
        'armor': 7,
        'evasion': 5,
        'will': 0,
        'fortitude': 50,
        'accuracy': 19,
        'move_speed': 0.5,
        'attack_speed': 0.5,
        'ai': ai.AI_Default,
        'description': 'Large stone golem, animated by magic. Slow but very strong.',
        'resistances': {'stunned' : 'immune', 'fire' : 1, 'cold' : 1, 'burning' : 'immune'},
        'shred': 2,
        'essence': [(70, 'earth')],
        'flags' : NO_CORPSE | NO_BREATH,
        'subtype':'construct',
    },
    'monster_alligator': {
        'name': 'alligator',
        'char': 'A',
        'color': libtcod.dark_green,
        'hp': 50,
        'strength_dice' : '1d24',
        'attack_bonus' : 5,
        'armor': 5,
        'evasion': 5,
        'will': 3,
        'fortitude': 10,
        'accuracy': 10,
        'move_speed': 0.85,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A hunting alligator. Moves swiftly in the water. Its rending teath are especially dangerous for '
                       'unarmored adventurers.',
        'resistances': {'cold': -1, 'frozen': -1},
        'attributes': ['attribute_fast_swimmer','attribute_rend'],
        'shred': 1,
        'subtype':'beast',
        'body_type':'beast'
    },
    'monster_bear': {
        'name': 'cave bear',
        'char': 'B',
        'color': libtcod.sepia,
        'hp': 50,
        'strength_dice' : '1d40',
        'attack_bonus' : 0,
        'armor': 3,
        'evasion': 6,
        'will': 10,
        'fortitude': 18,
        'accuracy': 15,
        'move_speed': 0.85,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A rudely awakened cave bear',
        'resistances': {'cold': 1, 'frozen': 1},
        'attributes': ['ability_berserk'],
        'body_type':'beast',
        'shred': 2,
        'subtype':'beast',
    },
    'monster_tunnel_spider': {
        'name': 'tunnel spider',
        'char': 's',
        'color': libtcod.gray,
        'body_type': 'insect',
        'hp': 15,
        'strength_dice' : '1d8',
        'attack_bonus' : 0,
        'armor': 1,
        'evasion': 17,
        'will': 3,
        'fortitude': 2,
        'accuracy': 26,
        'move_speed': 1.6,
        'attack_speed': 1.0,
        'on_hit': ['on_hit_poison'],
        'on_create': main.tunnel_spider_spawn_web,
        'ai': ai.AI_TunnelSpider,
        'description': 'An arachnid who hunts by trapping hapless prey in its webs. Fast, but fragile.',
        'shred': 1,
        'subtype':'insect',
        'flags': WEB_IMMUNE
    },
    'monster_witch': {
        'name': 'witch',
        'char': 'w',
        'color': libtcod.dark_purple,
        'hp': 25,
        'strength_dice' : '2d4',
        'attack_bonus' : 0,
        'spell_power' : 10,
        'armor': 0,
        'evasion': 10,
        'will': 16,
        'fortitude': 8,
        'accuracy': 50,
        'move_speed': 0.8,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A servant of dark magic',
        'resistances': {'death': 1, 'madness': 'immune'},
        'attributes': ['ability_fireball'],
        'essence': [(15, 'fire'),(10, 'arcane')],
        'shred': 0,
        'equipment': [{'none':30,'weapon_dagger':30,'weapon_messer':30},{'none':90,'book_lesser_fire':10},{'equipment_witch_hat':100}],
        'subtype':'human',
        'flags' : EVIL,
    },
    'monster_wolf': {
        'name': 'tundra wolf',
        'char': 'w',
        'color': libtcod.light_orange,
        'hp': 35,
        'strength_dice' : '1d18',
        'attack_bonus' : 2,
        'armor': 1,
        'evasion': 10,
        'will': 11,
        'fortitude': 14,
        'accuracy': 20,
        'move_speed': 1.1,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A great gray wolf. Hunts in packs.',
        'shred': 1,
        'modifier_category':'beast',
        'subtype':'beast',
    },
    'monster_corvid_silencer': {
        'name': 'corvid silencer',
        'char': 'c',
        'color': libtcod.dark_blue,
        'hp': 40,
        'strength_dice' : '2d12',
        'attack_bonus' : 0,
        'armor': 1,
        'evasion': 20,
        'will': 17,
        'fortitude': 9,
        'accuracy': 25,
        'move_speed': 1.0,
        'attack_speed': 1.5,
        'ai': ai.AI_Default,
        'body_type': 'avian',
        'description': 'A small raven-headed humanoid. '
                       'Silencers hunt rogue wizards, and can hide themselves from sight with magic.',
        'loot_level':3,
        'equipment': [{'weapon_katar':10,'weapon_dagger':30,'weapon_messer':30},{'equipment_leather_armor':50,'equipment_cloth_robes':50}],
        'attributes': ['ability_silence'],
        'shred': 1,
        'stealth':4,
        'modifier_category':None,
        'subtype':'humanoid',
    },
    'monster_corvid_acolyte': {
        'name': 'corvid acolyte',
        'char': 'c',
        'color': libtcod.dark_cyan,
        'hp': 30,
        'strength_dice' : '1d12',
        'attack_bonus' : 0,
        'spell_power': 14,
        'armor': 1,
        'evasion': 20,
        'will': 20,
        'fortitude': 8,
        'accuracy': 25,
        'move_speed': 1.0,
        'attack_speed': 1.5,
        'ai': ai.AI_Default,
        'body_type': 'avian',
        'description': 'A small raven-headed humanoid, armed with magic.',
        'loot_level':1,
        'equipment': [{'weapon_dagger':20},{'equipment_cloth_robes':20}],
        'attributes': [{'ability_defile': 20, 'ability_frozen_orb': 20, 'ability_ice_shards': 20,'ability_arcane_arrow': 20, 'ability_heat_ray': 20},
                       {'ability_defile': 20, 'ability_frozen_orb': 20, 'ability_ice_shards': 20,'ability_arcane_arrow': 20, 'ability_heat_ray': 20}],
        'shred': 1,
        'stealth':8,
        'modifier_category':None,
        'subtype':'humanoid',
        'essence': [(30, 'arcane')],
    },
    'monster_frost_wraith': {
        'name': 'frost wraith',
        'char': 'W',
        'color': libtcod.dark_cyan,
        'hp': 50,
        'strength_dice' : '1d32',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 15,
        'will': 10,
        'fortitude': 10,
        'accuracy': 25,
        'move_speed': 1.2,
        'attack_speed': 1.0,
        'ai': lambda: ai.AI_Ambush(5,10),
        'description': 'A lurking malign spirit, wreathed in ice. Its attacks pass right through most armor.',
        'resistances': {'physical' : 1, 'radiant' : -1},
        'attributes': ['attribute_ambush'],
        'flags' : NO_CORPSE | EVIL,
        'pierce': 5, # Dang!
        'stealth':0,
        'modifier_category':None,
        'subtype':'undead',
    },

    'monster_necromancer': {
        'name': 'necromancer',
        'char': 'N',
        'color': libtcod.dark_purple,
        'hp': 25,
        'strength_dice' : '2d18',
        'attack_bonus' : 0,
        'spell_power' : 15,
        'armor': 10,
        'evasion': 10,
        'will': 14,
        'fortitude': 10,
        'accuracy': 20,
        'move_speed': 0.8,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A decrepit skeleton with a golden symbol of The Restless emblazoned on its skull.',
        'resistances': {'death' : 'immune', 'stunned' : 1, 'poisoned' : 'immune', 'physical' : 1, 'radiance' : -1},
        'attributes': ['ability_defile','ability_corpse_dance'],
        'essence': [(40, 'death'),(25, 'arcane')],
        'shred': 0,
        'equipment': [{'none':30,'weapon_dagger':30},{'none':90,'book_lesser_death':10},{'equipment_cloth_robes':20}],
        'loot_level': 1,
        'subtype':'undead',
        'flags' : EVIL | NO_BREATH | NO_CORPSE,
    },

    'monster_skeleton': {
        'name': 'skeleton',
        'char': 's',
        'color': libtcod.dark_purple,
        'hp': 25,
        'strength_dice' : '1d24',
        'attack_bonus' : 2,
        'armor': 10,
        'evasion': 10,
        'will': 0,
        'fortitude': 13,
        'accuracy': 20,
        'move_speed': 1.1,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A decrepit skeleton brought to life by dark magic.',
        'resistances': {'death' : 'immune', 'stunned' : 1, 'poisoned' : 'immune', 'physical' : 1, 'radiance' : -1},
        'shred': 1,
        'subtype':'undead',
        'flags' : EVIL | NO_BREATH | NO_CORPSE,
    },

    'monster_plague_wight': {
        'name': 'plague wight',
        'char': 'w',
        'color': libtcod.light_green,
        'hp': 30,
        'strength_dice' : '1d26',
        'attack_bonus' : 2,
        'armor': 1,
        'evasion': 10,
        'will': 5,
        'fortitude': 10,
        'accuracy': 15,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'The twisted zombie of a plague victim. When killed, the plague magic will spill forth as a Blight.',
        'resistances': {'death' : 'immune', 'poisoned' : 'immune', 'radiance' : -1},
        'death_function' : {
            'function': 'on_death_summon',
            'monster': 'monster_blight',
            'duration': 10,
            'message': 'A plague cloud billows forth from the wight!',
        },
        'shred': 2,
        'subtype':'undead',
        'flags' : EVIL | NO_BREATH | NO_CORPSE,
    },

    'monster_blight': {
        'name': 'blight',
        'char': 'B',
        'color': libtcod.light_green,
        'hp': 50,
        'strength_dice' : '1d44',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 15,
        'will': 0,
        'fortitude': 100,
        'accuracy': 15,
        'move_speed': 1.2,
        'attack_speed': 0.8,
        'ai': ai.AI_Default,
        'description': 'A malign cloud of plague magic. It cannot be killed by mortal means, but will dissipate soon.',
        'resistances': {'rot' : 'immune'},
        'attributes': ['attribute_invulnerable'],
        'flags' : NO_CORPSE | NO_BREATH | EVIL,
        'shred': 1,
        'subtype':'elemental',
        'on_hit': ['on_hit_rot']
    },

    'monster_nosferatu': {
        'name': 'Nosferatu',
        'char': 'N',
        'color': libtcod.purple,
        'hp': 150,
        'strength_dice' : '1d50',
        'attack_bonus' : 20,
        'armor': 5,
        'evasion': 15,
        'will': 15,
        'fortitude': 15,
        'accuracy': 22,
        'move_speed': 1.0,
        'attack_speed': 2.0,
        'ai': ai.AI_Default,
        'attributes': {'perk_flying', 'ability_warp_weapon', 'ability_blink'},
        'description': 'Ancient vampire and servant to a dark god. Fast and dangerous in melee combat.',
        'resistances': {'death' : 'immune', 'stunned' : 1, 'poisoned' : 'immune', 'radiance' : -1},
        'flags' : NO_BREATH | EVIL,
        'shred': 3,
        'essence': [(15, 'fire')],
        'subtype':'undead',
    },
    'monster_demon_hunter': {
        'name': 'demon hunter',
        'char': 'H',
        'color': libtcod.dark_crimson,
        'hp': 65,
        'strength_dice' : '2d12',
        'attack_bonus' : 0,
        'armor': 2,
        'evasion': 20,
        'will': 20,
        'fortitude': 14,
        'accuracy': 25,
        'move_speed': 1.0,
        'attack_speed': 1.5,
        'ai': ai.AI_Default,
        'body_type': 'default',
        'description':  'A powerful fighter armed with sword and crossbow.'
                        'Demon Hunters willingly accept exile to hunt heretics and abominations.',
        'loot_level':2,
        'equipment': [{'weapon_rapier':30},{'weapon_crossbow':30},{'equipment_leather_armor':50,'equipment_cloth_robes':50}],
        'on_hit':['on_hit_judgement'],
        'shred': 0,
        'modifier_category':None,
        'subtype':'humanoid',
        'essence': [(50, 'radiance')],
    },

    'monster_fire_elemental': {
        'name': 'fire elemental',
        'char': 'E',
        'color': libtcod.flame,
        'hp': 32,
        'strength_dice' : '1d34',
        'attack_bonus' : 0,
        'armor': 1,
        'evasion': 12,
        'will': 5,
        'fortitude': 5,
        'accuracy': 22,
        'move_speed': 1.0,
        'attack_speed': 1.8,
        'ai': ai.AI_Default,
        'description': 'A roaring vortex of living flame. '
                       'It fights with searing fury, leaving its victims charred and burned',
        'resistances': {'fire' : 'immune'},
        'flags' : NO_CORPSE | NO_BREATH,
        'shred': 3,
        'subtype':'elemental',
        'on_hit': ['on_hit_burn']
    },
    'monster_earth_elemental': {
        'name': 'earth elemental',
        'char': 'E',
        'color': libtcod.sepia,
        'hp': 80,
        'strength_dice' : '1d24',
        'attack_bonus' : 0,
        'armor': 5,
        'evasion': 8,
        'will': 0,
        'fortitude': 50,
        'accuracy': 20,
        'move_speed': 0.5,
        'attack_speed': 0.5,
        'ai': ai.AI_Default,
        'description': 'A form of stone, sand, and soil given life. '
                       'Attacks hardly phase it as it lumbers steadily forward.',
        'resistances': {'physical' : 2, 'fire' : 1, 'cold' : 1},
        'flags' : NO_CORPSE | NO_BREATH,
        'shred': 2,
        'subtype':'elemental',
    },
    'monster_air_elemental': {
        'name': 'air elemental',
        'char': 'E',
        'color': libtcod.light_sky,
        'hp': 36,
        'strength_dice' : '1d18',
        'attack_bonus' : 0,
        'armor': 1,
        'evasion': 18,
        'will': 10,
        'fortitude': 0,
        'accuracy': 24,
        'move_speed': 2.2,
        'attack_speed': 1.2,
        'ai': ai.AI_Default,
        'description': 'A playful spirit made of whirling gusts of wind. '
                       'It moves swiftly, leaving swirling dust and leaves in its wake.',
        'resistances': {'physical' : 1, 'fire' : 1, 'cold' : 1},
        'flags' : NO_CORPSE | NO_BREATH,
        'shred': 1,
        'subtype':'elemental',
        'movement_type' : pathfinding.FLYING
    },
    'monster_water_elemental': {
        'name': 'water elemental',
        'char': 'E',
        'color': libtcod.azure,
        'hp': 55,
        'strength_dice' : '1d14',
        'attack_bonus' : 0,
        'armor': 2,
        'evasion': 12,
        'will': 5,
        'fortitude': 5,
        'accuracy': 16,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'An amorphous being of pure water. '
                       'Anything caught in its flows will struggle to move or evade attacks.',
        'resistances': {'physical' : 1, 'fire' : 'immune', 'cold' : -1},
        'flags' : NO_CORPSE | NO_BREATH,
        'shred': 2,
        'subtype':'elemental',
        'movement_type' : pathfinding.AQUATIC | pathfinding.NORMAL,
        'on_tick' : main.water_elemental_tick
    },
    'monster_ice_elemental': {
        'name': 'ice elemental',
        'char': 'E',
        'color': libtcod.lightest_gray,
        'hp': 20,
        'strength_dice' : '1d26',
        'attack_bonus' : 10,
        'armor': 3,
        'evasion': 12,
        'will': 5,
        'fortitude': 5,
        'accuracy': 18,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A frigid creature made of blue glacial ice. '
                       'Heat drains away in its presence, leaving an aura of winter in its absence.',
        'resistances': {'physical' : 1, 'fire' : -1, 'cold' : 'immune'},
        'flags' : NO_CORPSE | NO_BREATH,
        'shred': 2,
        'pierce': 1,
        'subtype':'elemental',
    },
    'monster_shimmering_sword': {
        'name': 'shimmering sword',
        'char': '/',
        'color': libtcod.lighter_sky,
        'hp': 5,
        'strength_dice' : '1d8',
        'armor': 3,
        'evasion': 18,
        'will': 0,
        'fortitude': 0,
        'accuracy': 28,
        'move_speed': 2.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A shimmering image of a sword, floating in the air and acting of its own accord.',
        'resistances': {'poison' : 'immune', 'fume' : 'immune', 'burning' : 'immune', 'death': 3, 'radiance': 3},
        'flags' : NO_CORPSE | NO_BREATH,
        'shred': 1,
        'pierce': 1,
        'subtype':'elemental',
        'movement_type' : pathfinding.FLYING,
    },
    'monster_lifeplant': {
        'name': 'lifeplant',
        'char': chr(5),
        'color': libtcod.green,
        'hp': 60,
        'body_type': 'plant',
        'strength_dice' : '0d0',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 0,
        'will': 0,
        'fortitude': 0,
        'accuracy': 0,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'on_tick': main.lifeplant_pulse,
        'description': 'A twisting, climbing vine adorned with golden flowers. '
                       'It glows with a soft warmth - those close enough to touch'
                       ' it can feel that warmth flow through them, healing their wounds.',
        'resistances': {'fire' : -1, 'stunned' : 'immune', 'poisoned' : 'immune', 'displacement' : 'immune',
                        'confusion' : 'immune'},
        'flags' : NO_CORPSE | IMMOBILE | NO_BREATH | LOW_PRIORITY,
        'shred': 3,
        'subtype':'plant',
    },
    'monster_arcane_construct': {
        'name': 'arcane construct',
        'char': 'A',
        'color': libtcod.fuchsia,
        'hp': 20,
        'strength_dice' : '0d0',
        'attack_bonus' : 0,
        'spell_power' : 8,
        'armor': 1,
        'evasion': 16,
        'will': 17,
        'fortitude': 0,
        'accuracy': 26,
        'move_speed': 1.0,
        'attack_speed': 0.4,
        'ai': ai.AI_Default,
        'attributes': ['ability_arcane_arrow'],
        'description': 'An artificial construct of glowing geometric shapes and symbols of power, '
                       'vibrating with arcane energy. '
                       'It bombards its enemies with magical energy from a distance.',
        'resistances': {'death' : 1, 'radiance' : 1},
        'shred': 0,
        'flags' : NO_CORPSE | NO_BREATH,
        'subtype':'elemental',
        'movement_type' : pathfinding.FLYING
    },
    'monster_guardian_angel': {
        'name': 'guardian angel',
        'char': 'A',
        'color': libtcod.light_yellow,
        'hp': 50,
        'strength_dice' : '3d22',
        'attack_bonus' : 2,
        'spell_power': 50,
        'armor': 3,
        'evasion': 18,
        'will': 35,
        'fortitude': 20,
        'accuracy': 25,
        'move_speed': 1.1,
        'attack_speed': 1.8,
        'ai': ai.AI_Default,
        'attributes': ['ability_smite'],
        'description': 'A mighty warrior angel in radiant golden armor.',
        'resistances': {'radiance' : 'immune', 'death' : 'immune'},
        'shred': 2,
        'subtype':'angel',
        'loot_level':15,
        'equipment': [{'weapon_greatsword':30,'weapon_halberd':30,'weapon_warhammer':30},{'equipment_plate_armor':100}],
        'movement_type': pathfinding.FLYING,
        'zombie':'monster_dark_angel'
    },
    'monster_infested_treant': {
        'name': 'infested treant',
        'char': 'T',
        'color': libtcod.dark_magenta,
        'hp': 180,
        'strength_dice' : '1d45',
        'attack_bonus' : 0,
        'armor': 4,
        'evasion': 4,
        'will': 5,
        'fortitude': 16,
        'accuracy': 22,
        'move_speed': 1.0,
        'attack_speed': 0.6,
        'ai': ai.AI_Default,
        'description': 'A walking hulk of rotting wood, crawling with roaches.',
        'resistances': {'fire' : -1},
        'on_get_hit' : 'on_damaged_summon_roaches',
        'shred': 1,
        'flags' : NO_CORPSE | NO_BREATH,
        'subtype' : 'treant',
    },
    'monster_blooming_treant': {
        'name': 'blooming treant',
        'char': 'T',
        'color': libtcod.dark_lime,
        'hp': 220,
        'strength_dice': '1d40',
        'attack_bonus': 0,
        'armor': 6,
        'evasion': 2,
        'will': 5,
        'fortitude': 14,
        'accuracy': 32,
        'move_speed': 0.87,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A towering, walking tree, covered in flowers and brightly-colored fungus.',
        'resistances': {'fire': -1},
        'attributes': ['ability_wild_growth'],
        'shred': 1,
        'flags': NO_CORPSE | NO_BREATH,
        'subtype': 'treant',
    },
    'monster_possessed_statue': {
        'name': 'possessed statue',
        'char': 'S',
        'color': libtcod.lightest_sepia,
        'hp': 80,
        'strength_dice': '0d0',
        'attack_bonus': 0,
        'armor': 10,
        'evasion': 0,
        'will': 15,
        'fortitude': 5,
        'accuracy': 32,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Sentry,
        'description': 'An ancient statue, its features worn away. A grim light glows from its stone eyes.',
        'resistances': {'fire': 2, 'cold': 2, 'lightning': 3, 'poisoned': 'immune', 'stunned': 'immune', 'burning': 'immune', 'toxic':'immune'},
        'attributes': ['ability_arcane_arrow'],
        'on_get_hit': 'on_damaged_teleport',
        'flags': NO_CORPSE | NO_BREATH | IMMOBILE,
        'subtype': 'inanimate',
    },
    'monster_dragon': {
        'name': 'dragon',
        'char': 'D',
        'color': libtcod.red,
        'hp': 200,
        'strength_dice' : '1d65',
        'attack_bonus' : 0,
        'armor': 5,
        'evasion': 4,
        'will': 18,
        'fortitude': 20,
        'accuracy': 28,
        'move_speed': 0.6,
        'attack_speed': 0.5,
        'ai': ai.AI_Default,
        'description': 'A terrifying dragon. Breathes fire. Fairly slow, but can deliver diving attacks.',
        'resistances': {'fire' : 'immune', 'burning' : 'immune', 'stunned' : 3},
        'shred': 2,
        'subtype' : 'dragon',
        'movement_type' : pathfinding.FLYING,
        'attributes' : ['ability_flame_breath','ability_great_dive']
    },
    'monster_scum_glob': {
        'name': 'scum glob',
        'char': 'O',
        'color': libtcod.dark_yellow,
        'hp': 125,
        'strength_dice' : '1d20',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 2,
        'will': 0,
        'fortitude': 8,
        'accuracy': 21,
        'move_speed': 1.0,
        'attack_speed': 0.75,
        'ai': ai.AI_Default,
        'description': 'An oozing pile of oil, mud, and filth. Everything it touches becomes greased with its slime. '
                       'Upon death, it divides itself into more, smaller globs.',
        'resistances': {'fire' : -1},
        'shred': 1,
        'flags' : NO_CORPSE,
        'death_function': {'function':'on_death_scum_glob'},
        'on_tick' : main.scum_glob_tick,
        'on_hit': ['on_hit_oil'],
        'on_create': main.scum_glob_on_create,
    },
    'monster_scum_glob_small': {
        'name': 'small scum glob',
        'char': 'o',
        'color': libtcod.dark_yellow,
        'hp': 35,
        'strength_dice' : '1d10',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 2,
        'will': 0,
        'fortitude': 8,
        'accuracy': 21,
        'move_speed': 1.0,
        'attack_speed': 0.75,
        'ai': ai.AI_Default,
        'description': 'A small, oozing pile of oil, mud, and filth. Everything it touches becomes greased with its slime. '
                       'It lacks the mass to divide upon death.',
        'resistances': {'fire' : -1},
        'shred': 1,
        'flags' : NO_CORPSE,
        'on_tick' : main.scum_glob_tick,
        'on_hit': ['on_hit_oil'],
        'on_create': main.scum_glob_on_create,
    },
    'monster_dragonweed': {
        'name': 'dragonweed',
        'char': 'W',
        'color': libtcod.dark_chartreuse,
        'hp': 85,
        'strength_dice' : '1d16',
        'attack_bonus' : 0,
        'armor': 3,
        'evasion': 0,
        'will': 0,
        'fortitude': 10,
        'accuracy': 26,
        'move_speed': 1.0,
        'attack_speed': 1.15,
        'ai': ai.AI_Sentry,
        'description': 'A thorny plant with scaly leaves. A long stem covered in thorns rises from the center, swaying '
                       'menacingly. It can grab prey from a distance and strangle it when it is near.',
        'shred': 3,
        'flags' : NO_CORPSE | IMMOBILE | NO_BREATH,
        'resistances': {'fire' : -1, 'stunned' : 'immune', 'poisoned' : 'immune', 'displacement' : 'immune',
                        'confusion' : 'immune'},
        'subtype' : 'plant',
        'body_type' : 'plant',
        'attributes' : ['ability_dragonweed_pull'],
        'on_hit': ['on_hit_immobilize'],
    },
    'monster_bloodfly': {
        'name': 'bloodfly',
        'char': 'b',
        'color': libtcod.pink,
        'hp': 32,
        'strength_dice': '1d8',
        'attack_bonus': 0,
        'armor': 0,
        'pierce': 1,
        'evasion': 12,
        'will': 0,
        'fortitude': 0,
        'accuracy': 18,
        'move_speed': 1.1,
        'attack_speed': 0.6,
        'ai': ai.AI_Default,
        'description': 'A bloated and mutated mosquito that scours the land in search of blood. '
                       'As it feeds, it grows healthier.',
        'shred': 1,
        'body_type': 'insect',
        'subtype': 'insect',
        'essence': [(20, 'life')],
        'on_create': main.bloodfly_on_create,
        'on_hit': ['on_hit_lifesteal'],
        'movement_type': pathfinding.FLYING,
    },
    'monster_arachnomancer': {
        'name': 'arachnomancer',
        'char': 'v',
        'color': libtcod.light_gray,
        'hp': 62,
        'strength_dice': '2d16',
        'attack_bonus': 0,
        'armor': 2,
        'evasion': 20,
        'will': 16,
        'fortitude': 4,
        'accuracy': 23,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A verman shrouded in cobwebs and crawling with spiders.',
        'resistances': {'poisoned' : 'immune', 'toxic' : 'immune'},
        'shred': 3,
        'subtype': 'verman',
        'essence': [(10, 'life'), (10, 'water')],
        'on_hit': ['on_hit_toxic'],
        'attributes' : ['ability_summon_spiders','ability_web_bomb'],
        'flags': WEB_IMMUNE,
        'loot_level':1,
        'equipment': [{'weapon_dagger':40, 'weapon_messer':30, 'weapon_rapier':30}, {'none':25,'equipment_cloth_robes':75}],
    },

    'monster_mycosaur': {
        'name': 'mycosaur',
        'char': 'M',
        'color': libtcod.fuchsia,
        'hp': 185,
        'strength_dice' : '1d50',
        'attack_bonus' : 0,
        'armor': 6,
        'evasion': 6,
        'will': 5,
        'fortitude': 18,
        'accuracy': 24,
        'move_speed': 0.8,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A great lumbering quadruped covered completely in multicolored fungi. '
                       'It breaths clouds of acrid fumes.',
        'shred': 2,
        'subtype' : 'beast',
        'movement_type' : pathfinding.NORMAL | pathfinding.AQUATIC,
        'flags': NO_BREATH,
        'attributes' : ['ability_reeker_breath']
    },

    'monster_cultist': {
        'name': 'cultist',
        'char': 'c',
        'color': libtcod.dark_purple,
        'hp': 15,
        'strength_dice': '2d12',
        'attack_bonus': 0,
        'armor': 1,
        'evasion': 12,
        'will': 17,
        'fortitude': 3,
        'accuracy': 10,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A crazed exile in service to some dark cult.',
        'shred': 0,
        'subtype': 'humanoid',
        'essence': [(10, 'death')],
        'attributes' : ['ability_summon_demon'],
        'loot_level':1,
        'equipment': [{'weapon_dagger':40}, {'none':25,'equipment_cloth_robes':75}],
    },
    'monster_servant_of_oblivion': {
        'name': "Servant of Oblivion",
        'char': 'S',
        'color': libtcod.dark_crimson,
        'hp': 200,
        'strength_dice': '1d96',
        'attack_bonus': 0,
        'armor': 5,
        'evasion': 20,
        'will': 20,
        'fortitude': 20,
        'accuracy': 25,
        'move_speed': 1.1,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'description': 'A horrific mass of spindly legs topped by an abyssal maw',
        'resistances': {'stunned' : 'immune', 'poisoned' : 'immune', 'cursed' : 'immune', 'doom' : 'immune'},
        'shred': 2,
        'subtype': 'demon',
        'essence': [(100, 'chaos')],
        'on_hit': ['on_hit_curse'],
        'flags': NO_CORPSE,
        'range':2
    },

    'monster_roiling_fury': {
        'name': 'roiling fury',
        'char': 'f',
        'color': libtcod.gray,
        'hp': 20,
        'strength_dice' : '1d12',
        'attack_bonus' : 0,
        'armor': 0,
        'evasion': 18,
        'will': 20,
        'fortitude': 6,
        'accuracy': 22,
        'move_speed': 1.0,
        'attack_speed': 1.0,
        'ai': ai.AI_Default,
        'body_type': None,
        'description': 'The essence of fury from stripped from something that once lived. Manifests itself as a heat'
                       'shimmer. Attacks with lightning.',
        'attributes': ['ability_lightning_storm'],
        'spell_power' : 20,
        'shred': 3,
        'stealth':2,
        'range': 2,
        'flags' : NO_CORPSE | NO_BREATH,
        'subtype':'elemental',
        'movement_type' : pathfinding.FLYING
    },
    'monster_gixian_ravager': {
        'name': 'Gixian Ravager',
        'char': 'G',
        'color': libtcod.dark_magenta,
        'hp': 100,
        'strength_dice' : '1d30',
        'attack_bonus' : 0,
        'armor': 4,
        'evasion': 10,
        'will': 8,
        'fortitude': 16,
        'accuracy': 20,
        'move_speed': 1.0,
        'attack_speed': 1.2,
        'ai': ai.AI_Default,
        'description': 'A undead mass of melted iron. ',
        'resistances': {'fire' : 2, 'burning': 2},
        'shred': 1,
        'flags' : EVIL,
        'subtype' : 'humanoid',
        'death_function' : {
            'function': 'on_death_summon',
            'monster': 'monster_shambling_iron',
            'duration': None,
            'message': '',
        },
    },
    'monster_shambling_iron': {
        'name': 'Shambling Iron',
        'char': 'i',
        'color': libtcod.gray,
        'hp': 50,
        'strength_dice' : '1d45',
        'attack_bonus' : 0,
        'armor': 9,
        'evasion': 10,
        'will': 2,
        'fortitude': 22,
        'accuracy': 14,
        'move_speed': 0.7,
        'attack_speed': 0.5,
        'ai': ai.AI_Default,
        'description': '',
        'resistances': {'fire' : 2, 'burning': 2},
        'shred': 1,
        'flags' : EVIL,
        'subtype' : 'undead',
        'death_function' : {
            'function': 'on_death_summon',
            'monster': 'monster_blight',
            'duration': None,
            'message': '',
        },
    }


}

modifiers = {
    '' : {},
    'brawny' : {
        'hp_bonus' : 1.25
    },
    'wimpy' : {
        'hp_bonus' : 0.75
    },
    'crazed' : {
        'damage_bonus' : 1.25
    },
    'mild' : {
        'damage_bonus' : 0.75
    },
    'nimble' : {
        'evasion_bonus' : 1.25,
        'speed_bonus' : 1.1
    },
    'lethargic' : {
        'evasion_bonus' : 0.75,
        'speed_bonus' : 0.8
    },
    'cursed' : {
        'hp_bonus' : 0.85,
        'evasion_bonus' : 0.85,
        'speed_bonus' : 1.25,
        'damage_bonus' : 1.25
    },
    'chosen of splug' : {
        'damage_bonus' : 1.25,
        'hp_bonus' : 1.5,
        'speed_bonus' : 1.1
    },
    'greased up' : {
        'speed_bonus' : 1.66,
        'evasion_bonus' : 1.33,
    },
    'adventurous' : {
        'hp_bonus': 1.25,
        'resistances' : {'fire' : 1, 'cold' : 1, 'stunned' : 1},
    },
    'alpha' : {
        'hp_bonus':1.25,
        'damage_bonus':1.25
    },
    'starved' : {
        'hp_bonus':0.8,
        'evasion_bonus':0.75
    },
    'lithe' : {
        'speed_bonus':1.25,
        'evasion_bonus':1.33
    },
    'scarred' : {
        'hp_bonus':1.33
    },
    'dire' : {
        'hp_bonus':1.5,
        'damage_bonus':1.5,
        'shred_bonus':1
    },
    'savage' : {
        'damage_bonus':1.5
    }
}

modifier_categories = {
    'default'   : {'':3,'brawny':1,'wimpy':1,'crazed':1,'mild':1,'nimble':1,'lethargic':1,'cursed':1},
    'goblin'    : {'':4,'brawny':2,'wimpy':3,'crazed':2,'nimble':2,'lethargic':3,'cursed':2,'chosen of splug':1,'greased up':1,'adventurous':2},
    'beast'     : {'':3,'brawny':1,'wimpy':1,'alpha':1,'starved':1,'lithe':1,'scarred':1,'dire':1,'savage':1},
}

import monsters_zombies
proto.update(monsters_zombies.proto)