import libtcodpy
from actions import item_actions
import player

table = {
#WEAPONS
    'weapon_longsword': {
        'name'               : 'longsword',
        'category'           : 'weapon',
        'subtype'            : 'sword',
        'damage_types'       : ['slashing'],
        'char'               : '/',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'right hand',
        'description'        : 'A hand-and-a-half cruciform sword',
        'stamina_cost'       : 10,
        'str_requirement'    : 10,
        'shred'              : 1,
        'accuracy'           : 1,
        'weapon_dice'        : '2d6',
        'str_dice'           : 2,
        'attack_delay'       : 14,
        'crit_bonus'         : 1.5
    },
    'weapon_rapier': {
        'name'               : 'rapier',
        'category'           : 'weapon',
        'subtype'            : 'sword',
        'damage_types'       : ['stabbing'],
        'char'               : '/',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'right hand',
        'description'        : 'A light, long, basket-hilted sword made for dueling',
        'stamina_cost'       : 6,
        'str_requirement'    : 8,
        'shred'              : 1,
        'accuracy'           : 1,
        'weapon_dice'        : '2d6',
        'str_dice'           : 2,
        'attack_delay'       : 12,
        'crit_bonus'         : 2.0
    },
    'weapon_greatsword': { #called a spadone or montante in historical circles, but no one will recognize that
        'name'               : 'greatsword',
        'category'           : 'weapon',
        'subtype'            : 'sword',
        'damage_types'       : ['slashing'],
        'char'               : '/',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'both hands',
        'description'        : 'A huge greatsword, made for fighting many foes at once.',
        'stamina_cost'       : 12,
        'str_requirement'    : 16,
        'shred'              : 2,
        'accuracy'           : 1,
        'weapon_dice'        : '3d6',
        'str_dice'           : 3,
        'attack_delay'       : 14,
        'crit_bonus'         : 1.5
    },
    'weapon_dagger': {
        'name'               : 'dagger',
        'category'           : 'weapon',
        'subtype'            : 'dagger',
        'damage_types'       : ['stabbing'],
        'char'               : '-',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'right hand',
        'description'        : 'A small double-edged knife. Deals triple damage to incapacitated targets',
        'stamina_cost'       : 6,
        'str_requirement'    : 6,
        'shred'              : 0,
        'accuracy'           : 5,
        'weapon_dice'        : '2d4',
        'str_dice'           : 1,
        'attack_delay'       : 12,
        'crit_bonus'         : 3.0
    },
    'weapon_messer': { #lit. german: 'knife'. no english period term
        'name'               : 'messer',
        'category'           : 'weapon',
        'damage_types'       : ['slashing'],
        'subtype'            : 'dagger',
        'char'               : '-',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'right hand',
        'description'        : 'A long knife, made for dueling',
        'stamina_cost'       : 8,
        'str_requirement'    : 8,
        'shred'              : 0,
        'accuracy'           : 5,
        'weapon_dice'        : '2d4',
        'str_dice'           : 2,
        'attack_delay'       : 12,
        'crit_bonus'         : 2
    },
    'weapon_katar': {
        'name'               : 'katar',
        'category'           : 'weapon',
        'damage_types'       : ['stabbing'],
        'subtype'            : 'dagger',
        'char'               : chr(19),
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'both hands',
        'description'        : 'A pair of exotic hooded punching daggers.',
        'stamina_cost'       : 6,
        'str_requirement'    : 8,
        'shred'              : 1,
        'accuracy'           : 5,
        'weapon_dice'        : '2d8',
        'str_dice'           : 2,
        'attack_delay'       : 10,
        'crit_bonus'         : 3.5
    },
    'weapon_spear': {
        'name'               : 'spear',
        'category'           : 'weapon',
        'subtype'            : 'polearm',
        'damage_types'       : ['stabbing'],
        'char'               : libtcodpy.CHAR_ARROW_N,
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'right hand',
        'description'        : 'A light thrusting spear',
        'stamina_cost'       : 10,
        'str_requirement'    : 8,
        'ability'            : 'ability_thrust',
        'pierce'             : 1,
        'shred'              : 0,
        'accuracy'           : 1,
        'ctrl_attack'        : player.reach_attack,
        'ctrl_attack_desc'   : 'Reach-Attack - attack an enemy up to 2 spaces away in this direction.',
        'weapon_dice'        : '2d10',
        'str_dice'           : 1,
        'attack_delay'       : 14,
        'crit_bonus'         : 1.5
    },
    'weapon_halberd': {
        'name'               : 'halberd',
        'category'           : 'weapon',
        'subtype'            : 'polearm',
        'damage_types'       : ['slashing'],
        'char'               : libtcodpy.CHAR_ARROW_N,
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               :'both hands',
        'description'        : 'A superior two-handed polearm with a spike, axe and hook on its head.',
        'stamina_cost'       : 12,
        'str_requirement'    : 16,
        'ability'            : 'ability_thrust',
        'pierce'             : 1,
        'shred'              : 0,
        'accuracy'           : 2,
        'ctrl_attack'        : player.reach_attack, #could use a special reach attack that cleaves
        'ctrl_attack_desc'   : 'Reach-Attack - attack an enemy up to 2 spaces away in this direction.',
        'weapon_dice'        : '3d6',
        'str_dice'           : 3,
        'attack_delay'       : 14,
        'crit_bonus'         : 1.5
    },
    'weapon_pickaxe': {
        'name'               : 'pickaxe',
        'category'           : 'weapon',
        'subtype'            : 'axe',
        'damage_types'       : ['stabbing'],
        'char'               : 'T',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'both hands',
        'description'        : 'A heavy digging implement used by miners. Can be used to dig through the walls '
                               'of the dungeon',
        'stamina_cost'       : 18,
        'str_requirement'    : 14,
        'pierce'             : 1,
        'shred'              : 1,
        'accuracy'           : -3,
        'ctrl_attack'        : item_actions.pickaxe_dig,
        'ctrl_attack_desc'   : 'Dig - dig through walls in this direction.',
        'break'              : 5.0,
        'weapon_dice'        : '1d4',
        'str_dice'           : 3,
        'attack_delay'       : 28,
        'crit_bonus'         : 1.5
    },
    'weapon_hatchet': {
        'name'               : 'hatchet',
        'category'           : 'weapon',
        'subtype'            : 'axe',
        'damage_types'       : ['slashing'],
        'char'               : 'p',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'right hand',
        'description'        : 'A one-handed axe made for cutting wood.',
        'stamina_cost'       : 9,
        'str_requirement'    : 8,
        'shred'              : 1,
        'accuracy'           : 3,
        'ctrl_attack'        : player.cleave_attack,
        'ability'            : 'ability_cleave',
        'ctrl_attack_desc'   : 'Cleave - attack all adjacent enemies. Costs 2x stamina.',
        'weapon_dice'        : '1d6',
        'str_dice'           : 2,
        'attack_delay'       : 16,
        'crit_bonus'         : 1.5
    },
    'weapon_dane_axe': {
        'name'               : 'dane axe',
        'category'           : 'weapon',
        'subtype'            : 'axe',
        'damage_types'       : ['slashing'],
        'char'               : 'P',
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'both hands',
        'description'        : 'A massive, two handed axe made for smashing shields and armor.',
        'stamina_cost'       : 12,
        'str_requirement'    : 16,
        'shred'              : 3,
        'accuracy'           : 3,
        'ctrl_attack'        : player.cleave_attack,
        'ability'            : 'ability_cleave',
        'ctrl_attack_desc'   : 'Cleave - attack all adjacent enemies. Costs 2x stamina.',
        'weapon_dice'        : '2d10',
        'str_dice'           : 3,
        'attack_delay'       : 16,
        'crit_bonus'         : 1.5
    },
    'weapon_mace': {
        'name'               : 'mace',
        'category'           : 'weapon',
        'subtype'            : 'mace',
        'damage_types'       : ['bludgeoning'],
        'char'               : chr(157),
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'right hand',
        'description'        : 'A one-handed flanged mace. Good against armored enemies',
        'stamina_cost'       : 10,
        'str_requirement'    : 10,
        'shred'              : 2,
        'accuracy'           : 2,
        'weapon_dice'        : '1d6',
        'str_dice'           : 2,
        'on_hit'             : ['on_hit_stun'],
        'attack_delay'       : 18,
        'crit_bonus'         : 1.5
    },
    'weapon_club': {
        'name'               : 'club',
        'category'           : 'weapon',
        'subtype'            : 'mace',
        'damage_types'       : ['bludgeoning'],
        'char'               : chr(157),
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'right hand',
        'description'        : 'A blunt piece of wood used for smashing things. The primitive weapon of brutes.',
        'stamina_cost'       : 10,
        'str_requirement'    : 6,
        'shred'              : 1,
        'accuracy'           : 2,
        'weapon_dice'        : '1d4',
        'str_dice'           : 1,
        'attack_delay'       : 20,
        'crit_bonus'         : 1.5,
        'allowed_materials'  : ['wooden']
    },
    'weapon_warhammer': {
        'name'               : 'warhammer',
        'category'           : 'weapon',
        'subtype'            : 'mace',
        'damage_types'       : ['bludgeoning'],
        'char'               : chr(157),
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'both hands',
        'description'        : 'A heavy hammer head mounted to a haft. Made for slaying armored foes outright.',
        'stamina_cost'       : 15,
        'str_requirement'    : 18,
        'shred'              : 2,
        'pierce'             : 3,
        'accuracy'           : 1,
        'weapon_dice'        : '1d8',
        'str_dice'           : 4,
        'on_hit'             : ['on_hit_stun'],
        'attack_delay'       : 20,
        'crit_bonus'         : 1.5
    },
    'weapon_coal_mace': {
        'name'               : 'coal-brazer mace',
        'category'           : 'weapon',
        'damage_types'       : ['fire'],
        'subtype'            : 'mace',
        'char'               : chr(157),
        'color'              : libtcodpy.yellow,
        'type'               : 'item',
        'slot'               : 'right hand',
        'description'        : 'A one-handed mace, fitted with a grate for burning coals.',
        'stamina_cost'       : 10,
        'str_requirement'    : 10,
        'shred'              : 2,
        'accuracy'           : 3,
        'weapon_dice'        : '1d8',
        'str_dice'           : 2,
        'on_hit'             : ['on_hit_stun'],
        'attack_delay'       : 18,
        'crit_bonus'         : 1.5
    },

    'weapon_crossbow': {
        'name'              : 'crossbow',
        'category'          : 'weapon',
        'damage_types'      : ['stabbing'],
        'subtype'           : 'ranged',
        'char'              : chr(23),
        'color'             : libtcodpy.yellow,
        'type'              : 'item',
        'slot'              : 'left hand',
        'description'       : "A crossbow, made so it can be worn over the left forearm. Can't be "
                              "reloaded during battle.",
        'str_requirement'   : 8,
        'shred'             : 2,
        'garunteed_shred'   : 1,
        'accuracy'          : 20,
        'weapon_dice'       : '2d10',
        'str_dice'          : 0,
        'attack_delay'      : 1000,
        'crit_bonus'        : 1.5,
        'range'             : 10,
        'ability'           : 'ability_off_hand_shot'

    }
}